const catalogs = {
  "zh-CN": {
    batchEmpty: "批量指令不能为空", batchLimit: "一次最多提交 {0} 条指令", itemLimit: "每条指令最多 3500 个字符", truncated: "…（已截断）",
    once: "仅允许这次", always: "本会话持续允许", reject: "拒绝", unknown: "未知", unknownSession: "未知会话",
    approvalTitle: "🔐 OpenCode 请求审批", session: "会话：{0}", permission: "权限：{0}", targets: "目标：\n{0}", details: "详情：\n{0}", directory: "目录：{0}", approvalPrompt: "请选择处理方式。任务会在你决定后继续。",
    seconds: "{0} 秒", minuteSeconds: "{0} 分 {1} 秒", minutes: "{0} 分钟", unnamedSession: "未命名会话", noAssistantReply: "暂无助手回复", noChanges: "暂无改动统计", changes: "改动 {0} 文件，+{1}/-{2}", sessionView: "【{0}】\n状态：{1}\n目录：{2}\n{3}\n待办：{4}\n\n最近回复：\n{5}",
    cmdSessions: "列出最近的 OpenCode 会话", cmdFind: "按标题或项目目录搜索会话", cmdCurrent: "查看当前选择的会话", cmdShow: "查看当前会话进展", cmdSend: "向当前会话发送一条指令", cmdAdd: "向当前会话队列追加一条指令", cmdBatch: "按 --- 分隔并依次执行多条指令", cmdQueue: "查看当前会话的指令队列", cmdPause: "暂停当前会话的自动队列", cmdResume: "恢复当前会话的自动队列", cmdClear: "清空等待中的队列指令", cmdStop: "停止当前会话的运行", cmdStatus: "查看服务状态", cmdHealth: "查看完整健康状态", cmdApprovals: "查看等待处理的审批", cmdHelp: "显示帮助",
    allowOnce: "✅ 仅允许这次", allowSession: "🔁 本会话持续允许", deny: "⛔ 拒绝", openCodeSession: "OpenCode 会话", approvalExpired: "审批已失效或 OpenCode 会话已关闭",
    queuePaused: "已暂停", queueAutomatic: "自动运行", none: "无", queueState: "队列状态：{0}", activeQueue: "当前队列任务：{0}", elapsed: "已运行：{0}", waitingCount: "等待数量：{0}", offline: "离线", online: "在线", unregistered: "未登记", notSelected: "未选择",
    health: "Agent Task Hub 健康状态\n\n界面语言：简体中文\nTelegram：已连接\nOpenCode Desktop：{0}\n插件实例：{1}\n可用会话：{2}\n当前会话：{3}\n待审批：{4}\n队列：运行 {5}，等待 {6}，暂停 {7}\n本次运行：{8}\n最近错误：{9}",
    selected: "已选择：{0}\n{1}\n目录：{2}", noSearch: "没有找到包含“{0}”的会话。", noSessions: "没有发现可连接的 OpenCode 会话。请先启动一次 OpenCode；插件加载后会自动登记本机实例。", previous: "⬅️ 上一页", next: "下一页 ➡️", searchHeading: "搜索“{0}”", sessionsHeading: "OpenCode 会话", page: "{0}（{1} 个，第 {2}/{3} 页）：\n\n{4}",
    unknownCommand: "无法识别。发送 /help 查看可用命令。", status: "服务在线。已登记本机 OpenCode 实例：{0}；当前会话：{1}", noApprovals: "目前没有等待处理的 OpenCode 审批。", sessionNotFound: "找不到该会话。请先发送 /sessions，再使用 /use 序号。", current: "当前会话：{0}\n{1}\n目录：{2}", selectFirst: "尚未选择会话，请先发送 /sessions。",
    queueFull: "当前会话队列已达到上限 {0} 条。", addStarted: "已追加并开始执行：\n{0}\n\n完成后会通知你；剩余等待：{1}", savedStartFailed: "指令已保存，但启动失败：{0}\n稍后可发送 /resume 重试。", added: "已追加 1 条指令。当前会话状态：{0}；等待数量：{1}", batchCapacity: "当前会话最多保留 {0} 条队列指令；现在还能加入 {1} 条。", batchStarted: "已接收 {0} 条指令，并开始第 1 条：\n{1}\n\n每条完成都会通知你；剩余等待：{2}", batchSavedFailed: "已保存 {0} 条指令，但启动失败：{1}\n稍后可发送 /resume 重试。", batchAdded: "已接收 {0} 条指令。当前会话状态：{1}；会在会话下一次完成后依次执行。等待数量：{2}", badQueueIndex: "没有这个队列序号。发送 /queue 查看等待列表。", removed: "已删除等待任务：\n{0}", paused: "自动队列已暂停。当前正在运行的任务不会被停止。", resumedStarted: "队列已恢复并开始下一条：\n{0}\n\n剩余等待：{1}", resumedFailed: "队列已恢复，但启动失败：{0}", resumed: "自动队列已恢复。当前会话状态：{0}。", queueEmpty: "等待队列已经是空的。", confirmClear: "确认清空 {0} 条等待任务？当前正在运行的任务不会被停止。", confirmClearButton: "确认清空", cancel: "取消", sent: "已发送给当前 OpenCode 会话。完成后会自动通知你。", confirmStop: "确认停止“{0}”当前正在执行的任务？", confirmStopButton: "确认停止",
    alreadyHandled: "该审批已处理或已失效", handled: "已处理：{0}", cancelled: "已取消", sessionUnavailable: "会话已不可用", setCurrent: "已设为当前会话", detailSent: "已发送详情", addHelp: "已选择“{0}”。\n\n追加一条：/add 指令内容\n批量提交：/batch 后按 --- 分隔。", queueSent: "已发送队列", stopRequested: "已请求停止", stopDone: "已向 OpenCode 发出停止请求，自动队列也已暂停。", currentChanged: "当前会话已改变", queueCleared: "等待队列已清空", queueClearedDetail: "等待队列已清空。当前正在运行的任务未受影响。", operationFailed: "操作失败：{0}", currentSession: "✅ 当前会话", setAsCurrent: "设为当前", viewDetails: "查看详情", append: "➕ 追加指令", viewQueue: "📋 查看队列", stopTask: "⏹ 停止任务",
    manualSource: "\n来源：电脑端手动任务", queueItem: "队列指令", itemProgress: "第 {0}/{1} 条", executionFailed: "执行失败", completed: "已完成", queueProgress: "\n队列：{0}{1}\n耗时：{2}\n剩余：{3} 条{4}", nextTask: "\n下一条：{0}", queueAutoPaused: "\n队列已自动暂停。", waitingWillStart: "\n已有 {0} 条新队列指令，将在通知后开始。", changeStats: "\n改动：{0} 文件，+{1}/-{2}", error: "\n错误：{0}", unknownError: "未知错误", latestReply: "\n\n最近回复：\n{0}", taskCompleted: "任务已完成", completion: "{0} OpenCode {1}\n{2}\n目录：{3}{4}{5}{6}", nextFailed: "队列下一条启动失败，指令已保留：{0}\n请发送 /resume 重试。", allDone: "🎉 “{0}”的队列已全部完成。", onlineAnnouncement: "Agent Task Hub 已上线。发送 /sessions 查看 OpenCode 会话。",
    help: "Agent Task Hub\n\n/sessions 2 — 查看会话列表第 2 页\n/find 项目名 — 搜索标题或目录\n/use 1 — 选择当前页面第 1 个会话\n/current — 当前会话\n/show — 查看当前进展与最近回复\n/send 内容 — 立即发送给当前会话\n/add 内容 — 向当前会话队列追加一条指令\n/batch — 批量提交多条指令；每条之间单独一行写 ---\n/queue — 查看当前会话队列\n/remove 2 — 删除第 2 条等待任务\n/pause — 暂停自动队列\n/resume — 恢复队列\n/clearqueue — 清空等待队列\n/stop — 停止当前运行\n/approvals — 查看等待处理的审批\n/health — 查看完整健康状态\n/status — 查看简要状态\n\n示例：\n/batch\n先给我内容\n---\n分析内容\n---\n写下文档"
  },
  "en-US": {
    batchEmpty: "Batch input cannot be empty", batchLimit: "A batch can contain at most {0} prompts", itemLimit: "Each prompt can contain at most 3,500 characters", truncated: "… (truncated)",
    once: "Allow once", always: "Allow for session", reject: "Reject", unknown: "Unknown", unknownSession: "Unknown session",
    approvalTitle: "🔐 OpenCode approval required", session: "Session: {0}", permission: "Permission: {0}", targets: "Targets:\n{0}", details: "Details:\n{0}", directory: "Directory: {0}", approvalPrompt: "Choose how to proceed. The task will continue after your decision.",
    seconds: "{0}s", minuteSeconds: "{0}m {1}s", minutes: "{0}m", unnamedSession: "Untitled session", noAssistantReply: "No assistant reply yet", noChanges: "No change summary", changes: "Changed {0} files, +{1}/-{2}", sessionView: "[{0}]\nStatus: {1}\nDirectory: {2}\n{3}\nPending todos: {4}\n\nLatest reply:\n{5}",
    cmdSessions: "List recent OpenCode sessions", cmdFind: "Search titles and project paths", cmdCurrent: "Show the selected session", cmdShow: "Show current session progress", cmdSend: "Send one instruction now", cmdAdd: "Append one queued instruction", cmdBatch: "Queue prompts separated by ---", cmdQueue: "Show the session queue", cmdPause: "Pause automatic queue progress", cmdResume: "Resume automatic queue progress", cmdClear: "Clear waiting queue items", cmdStop: "Stop the current run", cmdStatus: "Show service status", cmdHealth: "Show detailed health status", cmdApprovals: "Show pending approvals", cmdHelp: "Show command help",
    allowOnce: "✅ Allow once", allowSession: "🔁 Allow for session", deny: "⛔ Reject", openCodeSession: "OpenCode session", approvalExpired: "The approval expired or the OpenCode session closed",
    queuePaused: "paused", queueAutomatic: "automatic", none: "none", queueState: "Queue mode: {0}", activeQueue: "Active item: {0}", elapsed: "Elapsed: {0}", waitingCount: "Waiting: {0}", offline: "offline", online: "online", unregistered: "not registered", notSelected: "none",
    health: "Agent Task Hub health\n\nLanguage: English\nTelegram: connected\nOpenCode Desktop: {0}\nPlugin instances: {1}\nAvailable sessions: {2}\nSelected session: {3}\nPending approvals: {4}\nQueue: {5} running, {6} waiting, {7} paused\nUptime: {8}\nLatest error: {9}",
    selected: "Selected: {0}\n{1}\nDirectory: {2}", noSearch: "No session contains “{0}” in its title or path.", noSessions: "No OpenCode session is available. Start OpenCode once; the plugin will register the local instance after loading.", previous: "⬅️ Previous", next: "Next ➡️", searchHeading: "Search “{0}”", sessionsHeading: "OpenCode sessions", page: "{0} ({1} total, page {2}/{3}):\n\n{4}",
    unknownCommand: "Command not recognized. Send /help for available commands.", status: "Service online. Registered OpenCode instances: {0}; selected session: {1}", noApprovals: "There are no pending OpenCode approvals.", sessionNotFound: "Session not found. Send /sessions, then use /use with its number.", current: "Selected session: {0}\n{1}\nDirectory: {2}", selectFirst: "No session is selected. Send /sessions first.",
    queueFull: "This session queue has reached its {0}-item limit.", addStarted: "Added and started:\n{0}\n\nYou will be notified when it finishes. Waiting: {1}", savedStartFailed: "The prompt was saved but could not start: {0}\nSend /resume later to retry.", added: "Added one prompt. Session status: {0}; waiting: {1}", batchCapacity: "This session can hold {0} queue items; {1} slots remain.", batchStarted: "Accepted {0} prompts and started the first:\n{1}\n\nEach completion will be reported. Waiting: {2}", batchSavedFailed: "Saved {0} prompts but could not start: {1}\nSend /resume later to retry.", batchAdded: "Accepted {0} prompts. Session status: {1}; they will run in order after the current work. Waiting: {2}", badQueueIndex: "That queue number does not exist. Send /queue to view waiting items.", removed: "Removed waiting item:\n{0}", paused: "Automatic queue progress is paused. The active task continues.", resumedStarted: "Queue resumed and started the next item:\n{0}\n\nWaiting: {1}", resumedFailed: "Queue resumed but could not start: {0}", resumed: "Automatic queue progress resumed. Session status: {0}.", queueEmpty: "The waiting queue is already empty.", confirmClear: "Clear {0} waiting items? The active task will continue.", confirmClearButton: "Clear queue", cancel: "Cancel", sent: "Sent to the selected OpenCode session. You will be notified on completion.", confirmStop: "Stop the active task in “{0}”?", confirmStopButton: "Stop task",
    alreadyHandled: "This approval was already handled or expired", handled: "Handled: {0}", cancelled: "Cancelled", sessionUnavailable: "The session is unavailable", setCurrent: "Set as current session", detailSent: "Details sent", addHelp: "Selected “{0}”.\n\nAppend one: /add prompt\nAdd a batch: /batch with --- separators.", queueSent: "Queue sent", stopRequested: "Stop requested", stopDone: "The stop request was sent to OpenCode and automatic queue progress was paused.", currentChanged: "The selected session changed", queueCleared: "Waiting queue cleared", queueClearedDetail: "The waiting queue was cleared. The active task was not affected.", operationFailed: "Operation failed: {0}", currentSession: "✅ Current", setAsCurrent: "Set current", viewDetails: "View details", append: "➕ Add prompt", viewQueue: "📋 View queue", stopTask: "⏹ Stop task",
    manualSource: "\nSource: task started on the computer", queueItem: "queue item", itemProgress: "item {0}/{1}", executionFailed: "failed", completed: "completed", queueProgress: "\nQueue: {0} {1}\nDuration: {2}\nRemaining: {3}{4}", nextTask: "\nNext: {0}", queueAutoPaused: "\nThe queue was paused automatically.", waitingWillStart: "\n{0} queued prompts will start after this notification.", changeStats: "\nChanges: {0} files, +{1}/-{2}", error: "\nError: {0}", unknownError: "Unknown error", latestReply: "\n\nLatest reply:\n{0}", taskCompleted: "task completed", completion: "{0} OpenCode {1}\n{2}\nDirectory: {3}{4}{5}{6}", nextFailed: "The next queue item could not start and was retained: {0}\nSend /resume to retry.", allDone: "🎉 The queue for “{0}” is complete.", onlineAnnouncement: "Agent Task Hub is online. Send /sessions to view OpenCode sessions.",
    help: "Agent Task Hub\n\n/sessions 2 — show session page 2\n/find project — search titles or paths\n/use 1 — select item 1 on the current page\n/current — show the selected session\n/show — show progress and the latest reply\n/send prompt — send immediately\n/add prompt — append one queued prompt\n/batch — add prompts separated by a line containing ---\n/queue — show the selected session queue\n/remove 2 — remove waiting item 2\n/pause — pause automatic queue progress\n/resume — resume automatic queue progress\n/clearqueue — clear waiting items\n/stop — stop the active task\n/approvals — show pending approvals\n/health — show detailed health\n/status — show compact status\n\nExample:\n/batch\nInspect the issue\n---\nFix it and run tests\n---\nWrite maintenance notes"
  }
}

export function createI18n(language = "en-US") {
  const locale = catalogs[language] ? language : "en-US"
  const catalog = catalogs[locale]
  return {
    language: locale,
    t(key, ...args) {
      const template = catalog[key] ?? catalogs["en-US"][key] ?? key
      return String(template).replace(/\{(\d+)\}/g, (_, index) => String(args[Number(index)] ?? ""))
    },
    commands() {
      return [
        ["sessions", "cmdSessions"], ["find", "cmdFind"], ["current", "cmdCurrent"], ["show", "cmdShow"], ["send", "cmdSend"], ["add", "cmdAdd"], ["batch", "cmdBatch"], ["queue", "cmdQueue"], ["pause", "cmdPause"], ["resume", "cmdResume"], ["clearqueue", "cmdClear"], ["stop", "cmdStop"], ["status", "cmdStatus"], ["health", "cmdHealth"], ["approvals", "cmdApprovals"], ["help", "cmdHelp"],
      ].map(([command, key]) => ({ command, description: this.t(key) }))
    },
  }
}
