const catalogs = {
  "zh-CN": {
    batchEmpty: "批量指令不能为空", batchLimit: "一次最多提交 {0} 条指令", itemLimit: "每条指令最多 3500 个字符", truncated: "…（已截断）",
    once: "仅允许这次", always: "本会话持续允许", reject: "拒绝", unknown: "未知", unknownSession: "未知会话",
    approvalTitle: "🔐 OpenCode 请求审批", session: "会话：{0}", permission: "权限：{0}", targets: "目标：\n{0}", details: "详情：\n{0}", directory: "目录：{0}", approvalPrompt: "请选择处理方式。任务会在你决定后继续。",
    seconds: "{0} 秒", minuteSeconds: "{0} 分 {1} 秒", minutes: "{0} 分钟", unnamedSession: "未命名会话", noAssistantReply: "暂无助手回复", noChanges: "暂无改动统计", changes: "改动 {0} 文件，+{1}/-{2}", sessionView: "【{0}】\n状态：{1}\n目录：{2}\n{3}\n待办：{4}\n\n最近回复：\n{5}", codexSessionView: "【{0}】\nAgent：Codex\n状态：{1}\n目录：{2}\n轮次：{3}\n\n最近回复：\n{4}",
    cmdHome: "打开聚合首页", cmdSessions: "查看全部 Agent 会话", cmdOpenCode: "进入 OpenCode 模式", cmdCodex: "进入 Codex 模式", cmdCurrent: "查看当前选择的会话", cmdShow: "查看当前会话进展", cmdSend: "向当前会话发送一条指令", cmdAdd: "向当前会话队列追加一条指令", cmdBatch: "按 --- 分隔并依次执行多条指令", cmdQueue: "查看当前会话的指令队列", cmdHelp: "显示帮助",
    allowOnce: "✅ 仅允许这次", allowSession: "🔁 本会话持续允许", deny: "⛔ 拒绝", openCodeSession: "OpenCode 会话", approvalExpired: "审批已失效或 OpenCode 会话已关闭",
    queuePaused: "已暂停", queueAutomatic: "自动运行", none: "无", queueState: "队列状态：{0}", activeQueue: "当前队列任务：{0}", elapsed: "已运行：{0}", waitingCount: "等待数量：{0}", offline: "离线", online: "在线", unregistered: "未登记", notSelected: "未选择", codexPrivate: "私有连接", codexShared: "共享连接",
    health: "Agent Task Hub 健康状态\n\n界面语言：简体中文\nTelegram：已连接\nOpenCode Desktop：{0}\nCodex 适配器：{1}\n插件实例：{2}\n可用会话：{3}\n当前会话：{4}\n待处理请求：{5}\n队列：运行 {6}，等待 {7}，暂停 {8}\n本次运行：{9}\n最近错误：{10}",
    home: "Agent Task Hub\n\n当前入口：{0}\n当前会话：{1}\n\nOpenCode：{2} 个会话\nCodex：{3}", homeTitle: "Agent Task Hub · 运行看板", homeSelected: "当前选择：{0}", homePendingRequests: "待处理请求：OpenCode {0}；Codex {1}", homeRequestCount: "{0} 审批 / {1} 问题", homeAgentSummary: "{0} {1}：运行 {2} · 排队 {3} · 会话 {4}", homeNoRunning: "当前没有执行中的任务", homeRunningTask: "{0}. {1}\n   已运行 {2}{3}\n   {4}", homeBlocked: " · {0}", homeWaitingApproval: "等待审批", homeWaitingQuestion: "等待选择", homeWaitingBoth: "等待审批和选择", homeMoreRunning: "另有 {0} 个任务正在执行", homeRecentError: "⚠️ 最近异常：[{0}] {1}", unknownDuration: "时间未知", refresh: "🔄 刷新", globalMode: "聚合首页", openCodeMode: "OpenCode 模式", codexMode: "Codex 模式", codexNotConnected: "未连接", sessionCount: "{0} 个任务", codexUnavailable: "Codex 适配器连接失败：{0}\n\n你可以返回聚合首页或切换到 OpenCode。", selected: "已进入 {0} 模式\n\n当前会话：{1}\nID：{2}\n目录：{3}", noSearch: "没有找到包含“{0}”的会话。", noSessions: "当前入口没有发现可连接的会话。", previous: "⬅️ 上一页", next: "下一页 ➡️", searchHeading: "搜索“{0}”", sessionsHeading: "全部 Agent 会话", openCodeSessionsHeading: "OpenCode 会话", codexSessionsHeading: "Codex 任务", page: "{0}（{1} 个，第 {2}/{3} 页）：\n\n{4}", agentOpenCode: "OpenCode", agentCodex: "Codex", buttonHome: "🏠 聚合首页", buttonAllSessions: "🗂 全部会话", buttonOpenCode: "OpenCode", buttonCodex: "Codex", enterSession: "进入会话", agentModeUnavailable: "当前 {0} 模式尚不可用。",
    newUsage: "用法：/new 项目别名 | 第一条指令\n\n项目别名必须由管理员预先登记。", projectNotFound: "未登记 Codex 项目别名“{0}”。\n可用别名：{1}", projectUnavailable: "项目“{0}”的目录不可用：{1}", newStarted: "✅ 已创建 Codex 会话并开始执行\n\n项目：{0}\n任务：{1}\nID：{2}\n目录：{3}", newFailed: "创建 Codex 会话失败：{0}", steered: "已把补充要求加入当前正在运行的 Codex 轮次。", steerFailed: "无法追加到当前轮次：{0}", steerCodexOnly: "/steer 只适用于正在运行的 Codex 会话。OpenCode 请使用 /add 或 /send。",
    unknownCommand: "无法识别。发送 /help 查看可用命令。", status: "服务在线。已登记本机 OpenCode 实例：{0}\nCodex：{1}\n当前入口：{2}\n当前会话：{3}", noApprovals: "目前没有等待处理的审批。", noQuestions: "目前没有等待回答的问题。", sessionNotFound: "找不到该会话。请先发送 /sessions，再使用 /use 序号。", current: "当前会话：{0}\n{1}\n目录：{2}", selectFirst: "当前入口尚未选择可用会话，请先发送 /sessions。",
    queueFull: "当前会话队列已达到上限 {0} 条。", addStarted: "已追加并开始执行：\n{0}\n\n完成后会通知你；剩余等待：{1}", savedStartFailed: "指令已保存，但启动失败：{0}\n稍后可发送 /resume 重试。", added: "已追加 1 条指令。当前会话状态：{0}；等待数量：{1}", batchCapacity: "当前会话最多保留 {0} 条队列指令；现在还能加入 {1} 条。", batchStarted: "已接收 {0} 条指令，并开始第 1 条：\n{1}\n\n每条完成都会通知你；剩余等待：{2}", batchSavedFailed: "已保存 {0} 条指令，但启动失败：{1}\n稍后可发送 /resume 重试。", batchAdded: "已接收 {0} 条指令。当前会话状态：{1}；会在会话下一次完成后依次执行。等待数量：{2}", badQueueIndex: "没有这个队列序号。发送 /queue 查看等待列表。", removed: "已删除等待任务：\n{0}", paused: "自动队列已暂停。当前正在运行的任务不会被停止。", resumedStarted: "队列已恢复并开始下一条：\n{0}\n\n剩余等待：{1}", resumedFailed: "队列已恢复，但启动失败：{0}", resumed: "自动队列已恢复。当前会话状态：{0}。", queueEmpty: "等待队列已经是空的。", confirmClear: "确认清空 {0} 条等待任务？当前正在运行的任务不会被停止。", confirmClearButton: "确认清空", cancel: "取消", sent: "已发送给当前 OpenCode 会话。完成后会自动通知你。", confirmStop: "确认停止“{0}”当前正在执行的任务？", confirmStopButton: "确认停止",
    alreadyHandled: "该审批已处理或已失效", handled: "已处理：{0}", cancelled: "已取消", sessionUnavailable: "会话已不可用", setCurrent: "已设为当前会话", detailSent: "已发送详情", addHelp: "已选择“{0}”。\n\n追加一条：/add 指令内容\n批量提交：/batch 后按 --- 分隔。", queueSent: "已发送队列", stopRequested: "已请求停止", stopDone: "已向 OpenCode 发出停止请求，自动队列也已暂停。", stopDoneAgent: "已向 {0} 发出停止请求，自动队列也已暂停。", sentAgent: "已发送给当前 {0} 会话。完成后会自动通知你。", currentChanged: "当前会话已改变", queueCleared: "等待队列已清空", queueClearedDetail: "等待队列已清空。当前正在运行的任务未受影响。", operationFailed: "操作失败：{0}", currentSession: "✅ 当前会话", setAsCurrent: "设为当前", viewDetails: "查看详情", append: "➕ 追加指令", viewQueue: "📋 查看队列", stopTask: "⏹ 停止任务",
    codexApproval: "🔐 Codex 请求审批\n\n任务：{0}\n类型：{1}\n目录：{2}\n原因：{3}\n详情：\n{4}", codexQuestion: "❓ Codex 等待回答\n\n任务：{0}\n\n{1}\n\n点击选项，或发送 /answer 你的回答。", codexCommandApproval: "命令执行", codexFileApproval: "文件修改", codexPermissionApproval: "额外权限", codexApprovalHandled: "Codex 审批已处理", codexQuestionAnswered: "问题已回答", codexAnswerSaved: "回答已保存，请继续回答下一题", codexRequestExpired: "该 Codex 请求已处理、失效或连接已重启", cancelTask: "取消任务",
    openCodeQuestion: "❓ OpenCode 等待选择\n\n会话：{0}\n目录：{1}\n进度：{2}/{3}\n\n【{4}】\n{5}\n\n{6}\n\n{7}", question: "问题", noOptions: "可直接输入回答", multiChoiceHint: "可多选；选好后点击“提交选择”。", customAnswerHint: "点击选项，或发送 /answer 你的回答。", singleChoiceHint: "点击一个选项继续。", submitChoice: "✅ 提交选择", rejectQuestion: "忽略这个问题", questionExpired: "该问题已处理、失效或 OpenCode 会话已关闭", openCodeQuestionAnswered: "OpenCode 已收到回答", questionAnswerSaved: "回答已保存，请继续回答下一题", choiceUpdated: "选择已更新", questionRejected: "已忽略该问题",
    manualSource: "\n来源：电脑端手动任务", queueItem: "队列指令", itemProgress: "第 {0}/{1} 条", executionFailed: "执行失败", interrupted: "已中断", completed: "已完成", queueProgress: "\n队列：{0}{1}\n耗时：{2}\n剩余：{3} 条{4}", nextTask: "\n下一条：{0}", queueAutoPaused: "\n队列已自动暂停。", waitingWillStart: "\n已有 {0} 条新队列指令，将在通知后开始。", changeStats: "\n改动：{0} 文件，+{1}/-{2}", error: "\n错误：{0}", unknownError: "未知错误", latestReply: "\n\n最近回复：\n{0}", taskCompleted: "任务已完成", taskInterrupted: "任务已中断", completion: "{0} OpenCode {1}\n{2}\n目录：{3}{4}{5}{6}", completionAgent: "{0} [{1}] {2}\n{3}\n目录：{4}{5}{6}{7}", nextFailed: "队列下一条启动失败，指令已保留：{0}\n请发送 /resume 重试。", allDone: "🎉 “{0}”的队列已全部完成。", onlineAnnouncement: "Agent Task Hub 已上线。发送 /home 打开聚合首页。",
    help: "Agent Task Hub\n\n/home — 聚合首页\n/sessions — 全部 Agent 会话\n/opencode — OpenCode 入口\n/codex — Codex 入口\n/new 项目别名 | 指令 — 新建 Codex 会话\n/current — 当前模式和会话\n/show — 查看当前进展与最近回复\n/send 内容 — 立即发送给当前会话\n/steer 内容 — 补充当前运行中的 Codex 轮次\n/add 内容 — 追加一条队列指令\n/batch — 按单独一行的 --- 提交多条指令\n/queue — 查看当前会话队列\n\n选择会话后会自动进入对应 Agent 模式。高级命令继续可用，但不占用主菜单。"
  },
  "en-US": {
    batchEmpty: "Batch input cannot be empty", batchLimit: "A batch can contain at most {0} prompts", itemLimit: "Each prompt can contain at most 3,500 characters", truncated: "… (truncated)",
    once: "Allow once", always: "Allow for session", reject: "Reject", unknown: "Unknown", unknownSession: "Unknown session",
    approvalTitle: "🔐 OpenCode approval required", session: "Session: {0}", permission: "Permission: {0}", targets: "Targets:\n{0}", details: "Details:\n{0}", directory: "Directory: {0}", approvalPrompt: "Choose how to proceed. The task will continue after your decision.",
    seconds: "{0}s", minuteSeconds: "{0}m {1}s", minutes: "{0}m", unnamedSession: "Untitled session", noAssistantReply: "No assistant reply yet", noChanges: "No change summary", changes: "Changed {0} files, +{1}/-{2}", sessionView: "[{0}]\nStatus: {1}\nDirectory: {2}\n{3}\nPending todos: {4}\n\nLatest reply:\n{5}", codexSessionView: "[{0}]\nAgent: Codex\nStatus: {1}\nDirectory: {2}\nTurns: {3}\n\nLatest reply:\n{4}",
    cmdHome: "Open the aggregated home", cmdSessions: "List sessions from all agents", cmdOpenCode: "Enter OpenCode mode", cmdCodex: "Enter Codex mode", cmdCurrent: "Show the selected session", cmdShow: "Show current session progress", cmdSend: "Send one instruction now", cmdAdd: "Append one queued instruction", cmdBatch: "Queue prompts separated by ---", cmdQueue: "Show the session queue", cmdHelp: "Show command help",
    allowOnce: "✅ Allow once", allowSession: "🔁 Allow for session", deny: "⛔ Reject", openCodeSession: "OpenCode session", approvalExpired: "The approval expired or the OpenCode session closed",
    queuePaused: "paused", queueAutomatic: "automatic", none: "none", queueState: "Queue mode: {0}", activeQueue: "Active item: {0}", elapsed: "Elapsed: {0}", waitingCount: "Waiting: {0}", offline: "offline", online: "online", unregistered: "not registered", notSelected: "none", codexPrivate: "private connection", codexShared: "shared connection",
    health: "Agent Task Hub health\n\nLanguage: English\nTelegram: connected\nOpenCode Desktop: {0}\nCodex adapter: {1}\nPlugin instances: {2}\nAvailable sessions: {3}\nSelected session: {4}\nPending requests: {5}\nQueue: {6} running, {7} waiting, {8} paused\nUptime: {9}\nLatest error: {10}",
    home: "Agent Task Hub\n\nCurrent entry: {0}\nSelected session: {1}\n\nOpenCode: {2} sessions\nCodex: {3}", homeTitle: "Agent Task Hub · Live dashboard", homeSelected: "Selected: {0}", homePendingRequests: "Pending requests: OpenCode {0}; Codex {1}", homeRequestCount: "{0} approvals / {1} questions", homeAgentSummary: "{0} {1}: {2} running · {3} queued · {4} sessions", homeNoRunning: "No task is currently running", homeRunningTask: "{0}. {1}\n   Running for {2}{3}\n   {4}", homeBlocked: " · {0}", homeWaitingApproval: "waiting for approval", homeWaitingQuestion: "waiting for a choice", homeWaitingBoth: "waiting for approval and a choice", homeMoreRunning: "{0} more tasks are running", homeRecentError: "⚠️ Latest error: [{0}] {1}", unknownDuration: "unknown duration", refresh: "🔄 Refresh", globalMode: "aggregated home", openCodeMode: "OpenCode mode", codexMode: "Codex mode", codexNotConnected: "not connected", sessionCount: "{0} tasks", codexUnavailable: "The Codex adapter could not connect: {0}\n\nReturn home or switch to OpenCode.", selected: "Entered {0}\n\nSelected session: {1}\nID: {2}\nDirectory: {3}", noSearch: "No session contains “{0}” in its title or path.", noSessions: "No connected session is available in this entry.", previous: "⬅️ Previous", next: "Next ➡️", searchHeading: "Search “{0}”", sessionsHeading: "All agent sessions", openCodeSessionsHeading: "OpenCode sessions", codexSessionsHeading: "Codex tasks", page: "{0} ({1} total, page {2}/{3}):\n\n{4}", agentOpenCode: "OpenCode", agentCodex: "Codex", buttonHome: "🏠 Home", buttonAllSessions: "🗂 All sessions", buttonOpenCode: "OpenCode", buttonCodex: "Codex", enterSession: "Enter session", agentModeUnavailable: "The current {0} mode is not available.",
    newUsage: "Usage: /new project_alias | first prompt\n\nThe project alias must be registered by the administrator.", projectNotFound: "Codex project alias “{0}” is not registered.\nAvailable aliases: {1}", projectUnavailable: "The directory for project “{0}” is unavailable: {1}", newStarted: "✅ Created and started a Codex session\n\nProject: {0}\nTask: {1}\nID: {2}\nDirectory: {3}", newFailed: "Could not create the Codex session: {0}", steered: "Added the instruction to the active Codex turn.", steerFailed: "Could not steer the active turn: {0}", steerCodexOnly: "/steer is available only for an active Codex session. Use /add or /send for OpenCode.",
    unknownCommand: "Command not recognized. Send /help for available commands.", status: "Service online. Registered OpenCode instances: {0}\nCodex: {1}\nCurrent entry: {2}\nSelected session: {3}", noApprovals: "There are no pending approvals.", noQuestions: "There are no pending questions.", sessionNotFound: "Session not found. Send /sessions, then use /use with its number.", current: "Selected session: {0}\n{1}\nDirectory: {2}", selectFirst: "No available session is selected in this entry. Send /sessions first.",
    queueFull: "This session queue has reached its {0}-item limit.", addStarted: "Added and started:\n{0}\n\nYou will be notified when it finishes. Waiting: {1}", savedStartFailed: "The prompt was saved but could not start: {0}\nSend /resume later to retry.", added: "Added one prompt. Session status: {0}; waiting: {1}", batchCapacity: "This session can hold {0} queue items; {1} slots remain.", batchStarted: "Accepted {0} prompts and started the first:\n{1}\n\nEach completion will be reported. Waiting: {2}", batchSavedFailed: "Saved {0} prompts but could not start: {1}\nSend /resume later to retry.", batchAdded: "Accepted {0} prompts. Session status: {1}; they will run in order after the current work. Waiting: {2}", badQueueIndex: "That queue number does not exist. Send /queue to view waiting items.", removed: "Removed waiting item:\n{0}", paused: "Automatic queue progress is paused. The active task continues.", resumedStarted: "Queue resumed and started the next item:\n{0}\n\nWaiting: {1}", resumedFailed: "Queue resumed but could not start: {0}", resumed: "Automatic queue progress resumed. Session status: {0}.", queueEmpty: "The waiting queue is already empty.", confirmClear: "Clear {0} waiting items? The active task will continue.", confirmClearButton: "Clear queue", cancel: "Cancel", sent: "Sent to the selected OpenCode session. You will be notified on completion.", confirmStop: "Stop the active task in “{0}”?", confirmStopButton: "Stop task",
    alreadyHandled: "This approval was already handled or expired", handled: "Handled: {0}", cancelled: "Cancelled", sessionUnavailable: "The session is unavailable", setCurrent: "Set as current session", detailSent: "Details sent", addHelp: "Selected “{0}”.\n\nAppend one: /add prompt\nAdd a batch: /batch with --- separators.", queueSent: "Queue sent", stopRequested: "Stop requested", stopDone: "The stop request was sent to OpenCode and automatic queue progress was paused.", stopDoneAgent: "The stop request was sent to {0}, and automatic queue progress was paused.", sentAgent: "Sent to the selected {0} session. You will be notified on completion.", currentChanged: "The selected session changed", queueCleared: "Waiting queue cleared", queueClearedDetail: "The waiting queue was cleared. The active task was not affected.", operationFailed: "Operation failed: {0}", currentSession: "✅ Current", setAsCurrent: "Set current", viewDetails: "View details", append: "➕ Add prompt", viewQueue: "📋 View queue", stopTask: "⏹ Stop task",
    codexApproval: "🔐 Codex approval required\n\nTask: {0}\nType: {1}\nDirectory: {2}\nReason: {3}\nDetails:\n{4}", codexQuestion: "❓ Codex needs an answer\n\nTask: {0}\n\n{1}\n\nTap an option or send /answer followed by your answer.", codexCommandApproval: "command execution", codexFileApproval: "file changes", codexPermissionApproval: "additional permissions", codexApprovalHandled: "Codex approval handled", codexQuestionAnswered: "Question answered", codexAnswerSaved: "Answer saved; continue with the next question", codexRequestExpired: "This Codex request was handled, expired, or belongs to a closed connection", cancelTask: "Cancel task",
    openCodeQuestion: "❓ OpenCode needs a choice\n\nSession: {0}\nDirectory: {1}\nProgress: {2}/{3}\n\n[{4}]\n{5}\n\n{6}\n\n{7}", question: "Question", noOptions: "Enter a free-text answer", multiChoiceHint: "Select one or more choices, then tap Submit choices.", customAnswerHint: "Tap an option or send /answer followed by your answer.", singleChoiceHint: "Tap one option to continue.", submitChoice: "✅ Submit choices", rejectQuestion: "Ignore this question", questionExpired: "This question was handled, expired, or its OpenCode session closed", openCodeQuestionAnswered: "OpenCode received the answer", questionAnswerSaved: "Answer saved; continue with the next question", choiceUpdated: "Selection updated", questionRejected: "Question ignored",
    manualSource: "\nSource: task started on the computer", queueItem: "queue item", itemProgress: "item {0}/{1}", executionFailed: "failed", interrupted: "interrupted", completed: "completed", queueProgress: "\nQueue: {0} {1}\nDuration: {2}\nRemaining: {3}{4}", nextTask: "\nNext: {0}", queueAutoPaused: "\nThe queue was paused automatically.", waitingWillStart: "\n{0} queued prompts will start after this notification.", changeStats: "\nChanges: {0} files, +{1}/-{2}", error: "\nError: {0}", unknownError: "Unknown error", latestReply: "\n\nLatest reply:\n{0}", taskCompleted: "task completed", taskInterrupted: "task interrupted", completion: "{0} OpenCode {1}\n{2}\nDirectory: {3}{4}{5}{6}", completionAgent: "{0} [{1}] {2}\n{3}\nDirectory: {4}{5}{6}{7}", nextFailed: "The next queue item could not start and was retained: {0}\nSend /resume to retry.", allDone: "🎉 The queue for “{0}” is complete.", onlineAnnouncement: "Agent Task Hub is online. Send /home to open the aggregated home.",
    help: "Agent Task Hub\n\n/home — aggregated home\n/sessions — sessions from all agents\n/opencode — OpenCode entry\n/codex — Codex entry\n/new project_alias | prompt — create a Codex session\n/current — current mode and session\n/show — progress and latest reply\n/send prompt — send immediately\n/steer prompt — add input to the active Codex turn\n/add prompt — append one queued prompt\n/batch — submit prompts separated by a line containing ---\n/queue — selected session queue\n\nSelecting a session enters its agent mode automatically. Advanced commands remain available without occupying the main command menu."
  }
}

export function createI18n(language = "en-US") {
  const locale = catalogs[language] ? language : "en-US"
  const catalog = catalogs[locale]
  return {
    language: locale,
    t(key, ...args) {
      const template = catalog[key] ?? catalogs["en-US"][key] ?? key
      return String(template).replace(/\{(\d+)\}/g, (_, index) => String(args[Number(index)] ?? ""))
    },
    commands() {
      return [
        ["home", "cmdHome"], ["sessions", "cmdSessions"], ["opencode", "cmdOpenCode"], ["codex", "cmdCodex"], ["current", "cmdCurrent"], ["show", "cmdShow"], ["send", "cmdSend"], ["add", "cmdAdd"], ["batch", "cmdBatch"], ["queue", "cmdQueue"], ["help", "cmdHelp"],
      ].map(([command, key]) => ({ command, description: this.t(key) }))
    },
  }
}

export function localeKeys(language = "en-US") {
  return Object.keys(catalogs[catalogs[language] ? language : "en-US"]).sort()
}
